
services:

  database:
    image: postgres:15
    container_name: nachapa_database
    ports:
      - ${ENV_DB_PORT}:${ENV_DB_PORT}
    environment:
      POSTGRES_USER: ${ENV_DB_USERNAME}
      POSTGRES_PASSWORD: ${ENV_DB_PASSWORD}
      POSTGRES_DB: ${ENV_DB_PORT}
    env_file:
      .env
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - app_network


#  api:
#      container_name: main-api
#      # restart: always
#      build:
#          context: .
#          dockerfile: Dockerfile
#      environment:
#          SPRING_DATASOURCE_URL: jdbc:postgresql://${ENV_DB_URL}/${ENV_DB_NAME}
#          DB_USERNAME: ${ENV_DB_USERNAME}
#          DB_PASSWORD: ${ENV_DB_PASSWORD}
#          API_SECRET: ${ENV_API_SECRET}
#      env_file:
#          .env
#      networks:
#          - app_network
#      ports:
#          - ${ENV_SERVER_PORT}:${ENV_SERVER_PORT}
#      depends_on:
#          - database

networks:
  app_network:
    driver: bridge
